### ISSUE TITLE
First release tasks

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#11]
- [x] README:
  - [x] Remove pre-release warning. Provide basic info. #46
  - ~Add download, setup and build instructions #17~
- [x] Publish API reference to gh-pages #4, #5.
- [x] Publish to maven #10.
- ~Consider adding a RELEASING.md file like grpc-java #30~
- ~Ensure that release version number matches grpc core and/or grpc-java?~

cc @lowasser @dwiner @thisisnotapril - feel free to add items.

**Comment by chalin** [comment]
First release is out. Missing items have their own issues, so we can track them separately.
